import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useFetch } from "hooks";
import { DemoComponent, YoutubeComponent } from "components";

export default function Home() {
  // SWR call for all permissions
  const { GetTodos } = useFetch();
  const { data: todos } = GetTodos();

  console.log("index - response", todos);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <DemoComponent />
        <YoutubeComponent />
        <p className={styles.description}>
          <code className={styles.code}>Here are your todos:</code>
        </p>

        <div className={styles.grid}>
          {todos?.map((todo) => (
            <div key={todo.id} className={styles.card}>
              <h4>{todo.title}</h4>
              <p className={styles.subtitle}>
                {todo.completed ? "Completed" : "Not Completed"}
              </p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
